export const LAYER_IDS = Object.freeze({
  ocean: 'ocean-background',
  originalReference: 'original-reference',
  terrain: 'terrain-reference',
  countryMaskReference: 'countries-mask-reference',
  landFill: 'land-fill',
  unclaimedFill: 'unclaimed-fill',
  unclaimedBorder: 'unclaimed-border',
  countriesFill: 'countries-fill',
  countryLabels: 'country-labels',
  countryLabelPoints: 'country-label-points-debug',
  countryDebugIds: 'country-debug-ids',
  regionsFill: 'regions-fill',
  regionsBorder: 'regions-border',
  regionsLabels: 'regions-labels',
  capitalsPoint: 'capitals-point',
  capitalsLabel: 'capitals-label',
  debugRegionNumbers: 'debug-region-numbers',
  coastline: 'coastline',
  countriesBorderCasing: 'countries-border-casing',
  countriesBorder: 'countries-border',
  debugRawCountries: 'debug-countries-raw',
  debugCleanCountries: 'debug-countries-clean',
  debugCountryVertices: 'debug-country-vertices',
  debugUnassignedLand: 'debug-unassigned-land',
  debugLand: 'debug-land-extraction',
  debugLandFill: 'debug-land-overlay-fill',
  debugCountriesFill: 'debug-countries-extraction-fill',
  debugCountriesBorder: 'debug-countries-extraction-border',
  debugOriginalCountriesFill: 'debug-original-countries-fill',
  debugOriginalCountriesBorder: 'debug-original-countries-border',
  debugRegionsFill: 'debug-regions-fill',
  debugRegionsBorder: 'debug-regions-border',
  debugRegionsRaw: 'debug-regions-raw',
})

export const BASE_LAYER_ORDER = [
  LAYER_IDS.ocean,
  LAYER_IDS.landFill,
  LAYER_IDS.originalReference,
  LAYER_IDS.terrain,
  LAYER_IDS.unclaimedFill,
  LAYER_IDS.countriesFill,
  LAYER_IDS.regionsFill,
  LAYER_IDS.regionsBorder,
  LAYER_IDS.countriesBorderCasing,
  LAYER_IDS.countriesBorder,
  LAYER_IDS.unclaimedBorder,
  LAYER_IDS.coastline,
  LAYER_IDS.countryLabels,
  LAYER_IDS.countryLabelPoints,
  LAYER_IDS.countryDebugIds,
  LAYER_IDS.capitalsPoint,
  LAYER_IDS.regionsLabels,
  LAYER_IDS.capitalsLabel,
  LAYER_IDS.debugRegionNumbers,
  LAYER_IDS.countryMaskReference,
  LAYER_IDS.debugLand,
  LAYER_IDS.debugLandFill,
  LAYER_IDS.debugCountriesFill,
  LAYER_IDS.debugCountriesBorder,
  LAYER_IDS.debugOriginalCountriesFill,
  LAYER_IDS.debugOriginalCountriesBorder,
  LAYER_IDS.debugRegionsFill,
  LAYER_IDS.debugRegionsBorder,
  LAYER_IDS.debugRegionsRaw,
  LAYER_IDS.debugRawCountries,
  LAYER_IDS.debugCleanCountries,
  LAYER_IDS.debugCountryVertices,
  LAYER_IDS.debugUnassignedLand,
] as const
